"""Multi-role support

Revision ID: 4448bdba2da3
Revises: 0db737810f4f
Create Date: 2026-01-20 00:28:51.184598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4448bdba2da3'
down_revision: Union[str, Sequence[str], None] = '0db737810f4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roles', postgresql.ARRAY(sa.Enum('SAAS_OWNER', 'CARETAKER', 'LANDLORD', 'RESIDENT', 'SECURITY', name='user_role_enum', inherit_schema=True)), server_default='{resident}', nullable=False))
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('saas_owner', 'caretaker', 'landlord', 'resident', 'security', name='user_role_enum'), server_default=sa.text("'resident'::user_role_enum"), autoincrement=False, nullable=False))
    op.drop_column('users', 'roles')
    # ### end Alembic commands ###
