"""add property details to users and tokens

Revision ID: b26b17f615ca
Revises: e82a637beba6
Create Date: 2026-01-21 11:29:03.537650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b26b17f615ca'
down_revision: Union[str, Sequence[str], None] = 'e82a637beba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_tokens', sa.Column('house_number', sa.String(length=20), nullable=True))
    op.add_column('registration_tokens', sa.Column('street_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('house_number', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('street_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'street_name')
    op.drop_column('users', 'house_number')
    op.drop_column('registration_tokens', 'street_name')
    op.drop_column('registration_tokens', 'house_number')
    # ### end Alembic commands ###
