"""auto migration

Revision ID: ceb90e97239f
Revises: 
Create Date: 2026-01-19 23:48:08.887075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb90e97239f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estates',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('rfid_tag', sa.String(length=100), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('landlord_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_app_id'), 'users', ['app_id'], unique=False)
    op.create_index('ix_users_app_id_email', 'users', ['app_id', 'email'], unique=False)
    op.create_index('ix_users_app_id_rfid_tag', 'users', ['app_id', 'rfid_tag'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_rfid_tag'), 'users', ['rfid_tag'], unique=True)
    op.create_table('billings',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billings_app_id'), 'billings', ['app_id'], unique=False)
    op.create_index('ix_billings_app_id_user_id', 'billings', ['app_id', 'user_id'], unique=False)
    op.create_table('registration_tokens',
    sa.Column('code', sa.String(length=9), nullable=False),
    sa.Column('landlord_id', sa.Uuid(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['landlord_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reg_tokens_app_id_code', 'registration_tokens', ['app_id', 'code'], unique=False)
    op.create_index(op.f('ix_registration_tokens_app_id'), 'registration_tokens', ['app_id'], unique=False)
    op.create_index(op.f('ix_registration_tokens_code'), 'registration_tokens', ['code'], unique=True)
    op.create_table('subscriptions',
    sa.Column('estate_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['estate_id'], ['estates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estate_id')
    )
    op.create_table('visitor_tokens',
    sa.Column('code', sa.String(length=4), nullable=False),
    sa.Column('visitor_name', sa.String(length=255), nullable=False),
    sa.Column('resident_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('app_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['resident_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vis_tokens_app_id_code', 'visitor_tokens', ['app_id', 'code'], unique=False)
    op.create_index(op.f('ix_visitor_tokens_app_id'), 'visitor_tokens', ['app_id'], unique=False)
    op.create_index(op.f('ix_visitor_tokens_code'), 'visitor_tokens', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_tokens_code'), table_name='visitor_tokens')
    op.drop_index(op.f('ix_visitor_tokens_app_id'), table_name='visitor_tokens')
    op.drop_index('ix_vis_tokens_app_id_code', table_name='visitor_tokens')
    op.drop_table('visitor_tokens')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_registration_tokens_code'), table_name='registration_tokens')
    op.drop_index(op.f('ix_registration_tokens_app_id'), table_name='registration_tokens')
    op.drop_index('ix_reg_tokens_app_id_code', table_name='registration_tokens')
    op.drop_table('registration_tokens')
    op.drop_index('ix_billings_app_id_user_id', table_name='billings')
    op.drop_index(op.f('ix_billings_app_id'), table_name='billings')
    op.drop_table('billings')
    op.drop_index(op.f('ix_users_rfid_tag'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_app_id_rfid_tag', table_name='users')
    op.drop_index('ix_users_app_id_email', table_name='users')
    op.drop_index(op.f('ix_users_app_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('estates')
    # ### end Alembic commands ###
