"""standardize app_id as string

Revision ID: d54d51acff9c
Revises: 6418628d5f5e
Create Date: 2026-01-21 01:35:53.993811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd54d51acff9c'
down_revision: Union[str, Sequence[str], None] = '6418628d5f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billings', 'app_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.add_column('estates', sa.Column('app_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_estates_app_id'), 'estates', ['app_id'], unique=True)
    op.alter_column('registration_tokens', 'app_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('users', 'app_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('visitor_tokens', 'app_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visitor_tokens', 'app_id',
               existing_type=sa.String(length=50),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('users', 'app_id',
               existing_type=sa.String(length=50),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('registration_tokens', 'app_id',
               existing_type=sa.String(length=50),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_index(op.f('ix_estates_app_id'), table_name='estates')
    op.drop_column('estates', 'app_id')
    op.alter_column('billings', 'app_id',
               existing_type=sa.String(length=50),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
