"""increase reg code length

Revision ID: e7ed9df1260c
Revises: d54d51acff9c
Create Date: 2026-01-21 02:30:58.138296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ed9df1260c'
down_revision: Union[str, Sequence[str], None] = 'd54d51acff9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registration_tokens', 'code',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('registration_tokens', 'code',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    # ### end Alembic commands ###
