"""add is_revoked to registration tokens

Revision ID: e82a637beba6
Revises: e7ed9df1260c
Create Date: 2026-01-21 11:16:26.732255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82a637beba6'
down_revision: Union[str, Sequence[str], None] = 'e7ed9df1260c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_tokens', sa.Column('is_revoked', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration_tokens', 'is_revoked')
    # ### end Alembic commands ###
